// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-qHfb0pm216p3RoRpsRPxJku2SCsrW2Q',
    appId: '1:297522624233:web:a7923e456421ecffa96278',
    messagingSenderId: '297522624233',
    projectId: 'subway-seat',
    authDomain: 'subway-seat.firebaseapp.com',
    storageBucket: 'subway-seat.appspot.com',
    measurementId: 'G-E319XZG1E7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi55CsQmTAnReNWKOidOFTboKADBWwRDw',
    appId: '1:297522624233:android:13e698c849f47ed6a96278',
    messagingSenderId: '297522624233',
    projectId: 'subway-seat',
    storageBucket: 'subway-seat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiPFS8a4C5_unzox6dDokIYRKot9qFyNw',
    appId: '1:297522624233:ios:dba1a1c817aac4baa96278',
    messagingSenderId: '297522624233',
    projectId: 'subway-seat',
    storageBucket: 'subway-seat.appspot.com',
    iosBundleId: 'com.example.subwaySeat',
  );
}
